apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: orders-svc-credentials-vault
  namespace: orders-system
spec:
  vaultAuthRef: rabbitmq/vault-auth-prod
  mount: secret
  path: rabbitmq/orders
  type: kv-v2
  destination:
    name: orders-svc-credentials
    create: true
